### ISSUE TITLE
dir(nstx.s140000.mpts)

### ISSUE THREAD

**Issue by drsmith48** [Fusion-Data-Framework/fdf#11]
Is it possible to clean up dir() of diagnostic container with _ _ dir _ _ method?  dir(nstx) and dir(nstx.s140000) give nice output.

Presently:

> > > dir(nstx.s140000.mpts)
> > > ['**class**', '**delattr**', '**dict**', '**doc**', '**format**', '**getattr**', '**getattribute**', '**hash**', '**init**', '**module**', '**new**', '**reduce**', '**reduce_ex**', '**repr**', '**setattr**', '**sizeof**', '**str**', '**subclasshook**', '**weakref**', '_classes', '_diagnostic', '_instances', '_name', '_parent', '_radius', '_root', '_time', 'comment', 'mdspath', 'mdstree', 'ne', 'plot', 'shot', 'spline', 'te', 'valid']

**Comment by ktritz** [comment]
Done, though some things might need to be cleaned up at the signal level. Private attributes starting with '_' are filtered out, but there are some attributes that don't have the underscore that probably should, like 'slic'.
