### ISSUE TITLE
Data localization

### ISSUE THREAD

**Issue by izacard** [Fusion-Data-Framework/fdf#16]
It is not clear how to access the data of each diagnostic. Following is an example, I tried to access the 2D array `te(radius,time)` from mpts
> `import fdf`
> `nstx1 = fdf.Machine('nstx',[128638])`
`('mpts', 'root', <machine nstx>)`
`('mpts', 'diagnostic', 'mpts')`
`('usxr', 'root', <machine nstx>)`
`('usxr', 'diagnostic', 'usxr')`
`('vloop', 'root', <machine nstx>)`
`('vloop', 'diagnostic', 'vloop')`
`('ip', 'root', <machine nstx>)`
`('ip', 'diagnostic', 'ip')`
`Precaching MDS server connections...`
`Finished.`
> `dir(nstx1)`
`['s0', 's128638']`
> `dir(nstx1.s128638)`
`['ip', 'mpts', 'usxr', 'vloop']`
> `dir(nstx1.s128638.mpts)`
`['comment', 'ne', 'plot', 'shot', 'spline', 'te', 'valid']`
> `dir(nstx1.s128638.mpts.te)`
`['axes', 'axes_units', 'radius', 'slic', 'time', 'units']`
> `dir(nstx1.s128638.mpts.te.slic)`
`['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']`
> `print(nstx1.s128638.mpts.te)`
`[]`
> `print(nstx1.s128638.mpts.te.data)`
` `

**Comment by izacard** [comment]
It looks like the following commands are working
`te = nstx.s128638.mpts.te[:,:]`
`r = nstx.s128638.mpts.te.radius[:]`
`t = nstx.s128638.mpts.te.time[:]`

**Comment by drsmith48** [comment]
@hyyuh @ktritz - any comments on this issue?

**Comment by ktritz** [comment]
Yes, we have to be a bit careful of when to load the data. We could have it load with a call to **repr**, which is what is invoked by print, but that might get called inadvertently during other commands like dir, and you might end up loading a lot of data that you didn't want. We can test it to see.

For now, you need to invoke a get_item call, such as with [:] as you found, to actually load the data from MDSplus. This is to allow the entire model tree to exist as objects, without loading in all of the data for the whole tree.

**Comment by hyyuh** [comment]
I think I promised that the data get would be triggered by a repr() so I'll make that happen.
If you print(signal), it should fetch the data just as plot(signal) does.

**Comment by hyyuh** [comment]
I merged a modification of __str __ (for print) and __repr __ in fdf_signal.py.
We'll fetch it to /p/fdf when we have the write permissions sorted out with the p drive sys admins.
