### ISSUE TITLE
signals with different 'time' axes in the same container

### ISSUE THREAD

**Issue by drsmith48** [Fusion-Data-Framework/fdf#36]
Some groups of signals, like filterscopes, have different time axes.  It seems as if containers/signals/axes are designed for 1 time axis per container level.  I think we need a mechanism to specify multiple time axes in a single container level.  Maybe we need a mechanism to distinguish between axis name ('time') and axis label ('time_baye_haifa')?  This way, baye_haifa and bayg_haifa can be signals with a 'time' attribute in the same container, but the time attributes point to different time axes.  Thoughts?

**Comment by ktritz** [comment]
This already has been implemented. Not sure if one of the xml files shows
how. There is a tag either axis_ref or something similar that specifies the
name of the axis you want to use.

**Comment by ktritz** [comment]
Looking at the code, I think the xml uses 'axis_refs' to refer to the name
of the axis. So you would use it like this:

<axis name='time1' units='s' mdsnode='ts_times1'></axis> <axis name='time2'
units='s' mdsnode='ts_times2'></axis> <signal name='te1' units='keV'
axes='radius,
time' axis_refs='radius, time1' error='fit_te_err' mdsnode='fit_te1'
title='Electron
Temperature'> <signal name='te2' units='keV' axes='radius, time'
axis_refs='radius,
time2' error='fit_te_err' mdsnode='fit_te2' title='Electron Temperature'>
that way the signals te1 and te2 would both have a .time axis that would
point to a different axis signal.

**Comment by drsmith48** [comment]
Thanks, and a small correction for your example:
1) 'name' in axis element should match 'axes' in signal element
2) 'axis_refs' needs to be in both axis and signal elements
For example:

```
    <axis name='time' axis_ref='time1' units='s' mdsnode='dim_of(\bayg_dalpha_eies)'></axis>
    <signal name='bayg_dalpha_eies' units='AU' axes='time' axis_ref='time1' mdsnode='\bayg_dalpha_eies' desc='midplane tangential'></signal>
```

**Comment by hyyuh** [comment]
This needs to make it into the XML doc.

**Comment by ktritz** [comment]
Hmm, I don't remember it being like that. I'll have to take a closer look
at the code bc
