### ISSUE TITLE
exposing more signal attributes

### ISSUE THREAD

**Issue by drsmith48** [Fusion-Data-Framework/fdf#37]
In 'signal_dict' in factory.parse_signal(), I think that more signal attributes should be exposed for the user to inspect.  Specifically, I think that we should remove the underscore before name, mdsnode, mdstree, and desc.  Thoughts?

**Comment by ktritz** [comment]
The question is, what do you want to show up when people try to tab
complete. The attributes with underscores are supposed to be rarely
accessed by the user, and we hide them to avoid cluttering up the workflow.
I think right now it's hidden from the 'dir' command, but we could have
another command to list the entire contents of the **dict**.

I'm not set on hiding all of those you listed, that was just a default
behavior. What do others think?

**Comment by hyyuh** [comment]
We've discussed this before. I think there should be 2 levels of dir(). One
that only exposes signals and containers while the other shows most of the
others we're talking about.  Maybe dir and dir(/all)? Or /verbose?

**Comment by drsmith48** [comment]
@hyyuh - I don't think the first type of dir() you wrote about applies to signals.  If I understand things correctly, the first dir() you mention exposes only the iterable items under machine/shot/diagnostic/container.  In contrast, signal does not possess iterable elements, and dir(signal) can simply list visible attributes, which is the normal function of dir() I think.  That said, I like the idea of 'dir all'.

**Comment by drsmith48** [comment]
copied to FDP repo.
