### ISSUE TITLE
signal/container feature requests

### ISSUE THREAD

**Issue by drsmith48** [Fusion-Data-Framework/fdf#46]
Four feature requests:
1. Handle methods with names different than module name
   - e.g. `<method name=‘binAvgFft’ module=‘fft'>` for method binAvgFft() in fft.py
2. Rename methods
   - e.g. `<method name=‘fft’ ref_name=‘doubleSidedFft'>` so highk.ch01.fft() can wrap doubleSidedFft()
3. Container-level methods for multi-signal analysis
   - e.g. `<containermethod>` for highk.deltaNSpectrum() or magnetics.highn.torModeSpectrum()
4. Cache auxiliary calculations to avoid re-computing
   - e.g. bes.ch01.fft() somehow stores fft calculation in bes.ch01 to avoid re-computing if fft parameters do not change

**Comment by ktritz** [comment]
Container methods should already be implemented, the old mpts plot for
example. It's up to the method to be aware if it invoked by a container or
a signal. You can check if Container is in the class name. I suppose we
could add a specific function to return the type of object.

Similarly, the method can already cache results if it wants. I'm not sure
we need anything special in the framework code for that.

**Comment by drsmith48** [comment]
ok, thanks.  I see how 3 and 4 are already feasible.  I think 1 and 2 can be accomplished with methods/modules wrapping other methods/modules, but that seems a bit inelegant.  I'll take a crack at 1 and 2.
Also, FYI, simple isContainer(), etc methods are in test.py.

**Comment by drsmith48** [comment]
I added isContainer() and similar methods to factory.py.  They'll appear in a subsequent merge.  I think all items in this issue have been addressed.
